### ISSUE TITLE
How to use:

### ISSUE THREAD

**Issue by fzl122122** [chadlrnsn/wuwa-moonlight#1]
Hopefully there will be a tutorial on how to use it

**Comment by chadlrnsn** [comment]
> Hopefully there will be a tutorial on how to use it

There will be a guide, but after I make a working version

**Comment by fzl122122** [comment]
> > 希望会有一个关于如何使用它的教程希望会有一个关于如何使用它的教程
> 
> 会有一个指南，但在我制作工作版本之后会有一个指南，但在我制作工作版本之后

How much longer? Can you add a picture tutorial?

**Comment by chadlrnsn** [comment]
> How much longer? Can you add a picture tutorial?

Planned to finish today but today stretched into tomorrow, or maybe the day after tomorrow.

**Comment by fzl122122** [comment]
> > 还要多久？你能添加一个图片教程吗？
> 
> 计划今天完成，但今天延伸到明天，或者后天。

Ok, I'm waiting, hopefully the tutorial can be a little more detailed, I'm a bit dumb. I'm a big fan of yours

**Comment by Anto426** [comment]
Hi, is there still a long wait for a guide?

**Comment by chadlrnsn** [comment]
I wrote guide for upcoming version in dev branch but if you want touch this version u can read simple guide at my discord server that specified in the description, also there you can download pipsi's bypass

@Anto426 @fzl122122
