### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by fzl122122** [chadlrnsn/wuwa-moonlight#4]
Hello, I hope you can increase the function of Double Effort. And you can freely set the hotkey to turn on and off. I have a doubt, what is ESP, there is nothing in it

**Comment by chadlrnsn** [comment]
ESP in dev yet. What is "Double Effort" can you explain?

**Comment by fzl122122** [comment]
> ESP 在开发中。你能解释一下什么是“双倍努力”吗？

Hit multiplier。There is more damage when attacking

**Comment by fzl122122** [comment]
Dear author, I hope you can also launch a feature that makes enemies incapacitated, "Stupid", during the use of God mode, I found that God mode seems to have some bugs, it does not make itself invincible, but makes enemies invincible or non-life invincible in the world, just like taking a fireball and not being able to burn Fujiman. The above content is just a suggestion, the author is free to update, thank you

**Comment by OAndroid** [comment]
Dear author, can you make the injector launch w/ the -fileopenlog in path (like pipsi), because I want to use your wuwa enhancer with Kunmod at the same time.

Example: Your injector only work when path is: xxx\Client-Win64-Shipping.exe, but pipsi can work with xxx\Client-Win64-Shipping.exe -fileopenlog

**Comment by OAndroid** [comment]
> > -fileopenlog
> 
> I'll do it in the next update

Thanks for update, author. But I think there is a mistake. I open and edited cfg.ini to UseAdditionalParam = true, then I open Moonlight and it said -freeopenlog, not -fileopenlog. So in-game, KunMod doesnt work.

**Comment by chadlrnsn** [comment]
[Fixed](https://github.com/chadlrnsn/wuwa-moonlight/commit/61484285e15d071682d381abf151e52c98d32c84) but in dev branch, you can compile it self

**Comment by OAndroid** [comment]
Thanks sir.
