### ISSUE TITLE
Doesn't show the gui

### ISSUE THREAD

**Issue by x2b1** [chadlrnsn/wuwa-moonlight#5]
when i open it then it fails to create a gui

**Comment by chadlrnsn** [comment]
Try to disable all overlays

**Comment by havok585** [comment]
how confident are u  that the bypass from pipsi can block wuwa anticheat  ? since his update was obsolete since the latest update.
i managed to open the console, but i see no bypass.dll succesfully attached in the status window message, so i stopped in the main menu.
