### ISSUE TITLE
CMake Error at CMakeLists.txt:2 (project):

### ISSUE THREAD

**Issue by Littlei0409** [chadlrnsn/wuwa-moonlight#9]
I use Visual Studio 2022, but I don’t know why this error is still displayed.

Preset CMake variables:

  CMAKE_CXX_COMPILER="cl.exe"
  CMAKE_CXX_STANDARD="17"
  CMAKE_CXX_STANDARD_REQUIRED="ON"
  CMAKE_C_COMPILER="cl.exe"
  CMAKE_INSTALL_PREFIX="E:/bin/Release-x64/wuwa-moonlight/out/install/win-amd64"

CMake Error at CMakeLists.txt:2 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!

**Comment by chadlrnsn** [comment]
generate CmakePresets for VS 17 2022 configuration using chatgpt

**Comment by chadlrnsn** [comment]
Nah, there is already done presets for all msvcs. You should [select](https://github.com/user-attachments/assets/80260d2f-90cb-4c0c-8a62-fc6059d19494) preset for vs 2022 in bottom of your vscode. I don't remember, it's possible this build may not have built, in this 32524b097a3bf827b64e6556e3012085d151a402 commit you have 100% build if you specify the preset correctly.

**Comment by chadlrnsn** [comment]
Closing for now assuming it is fixed.
